Repository rexyai/RestRserve, pull requests merged in 2019-09, with the labels that each got.

#71 introduce from_rserve method for request object
  R/AuthBackend.R
  R/AuthBackendBasic.R
  R/AuthBackendBearer.R
  R/ContentHandlers.R
  R/HTTPError.R
  R/RestRserveApplication.R
  R/RestRserveRequest.R
  R/RestRserveResponse.R
  R/RestRserveRouter.R
  R/json.R
  R/openapi.R
  R/utils.R
  inst/examples/auth-basic/app.R
  inst/examples/deploy-start-stop/app-management.R
  inst/examples/deploy-start-stop/app.R
  inst/examples/fibonacci-numbers-rcpp/app.R
  inst/examples/fibonacci-numbers/app.R
  inst/examples/hello/app.R
  inst/examples/html-form/app.R
  inst/examples/openapi/app.R
  inst/examples/plot-magick/app.R
  inst/examples/predict-lm/app.R
  inst/examples/xgboost-mushrooms/app.R
  inst/http_request.R
  inst/tinytest/test-app-auth-basic.R
  inst/tinytest/test-app-auth-bearer.R
  inst/tinytest/test-app-compress.R
  inst/tinytest/test-app-content-handlers.R
  inst/tinytest/test-app-hello.R
  inst/tinytest/test-cl-application.R
  inst/tinytest/test-cl-auth-barear.R
  inst/tinytest/test-cl-auth.basic.R
  inst/tinytest/test-cl-request.R
  inst/tinytest/test-cl-response.R
  inst/tinytest/test-cl-router.R
  inst/tinytest/test-misc.R
  man/AuthBackendBasic.Rd
  man/AuthBackendBearer.Rd
  man/HTTPErrorFactory.Rd
  man/RestRserveApplication.Rd
  man/RestRserveRequest.Rd
  man/RestRserveResponse.Rd
  man/RestRserveRouter.Rd
  man/openapi.Rd
  man/to_json.Rd
  tests/tinytest.R
Labels: core, enhancement, performance

#82 Check fixes
  NAMESPACE
  R/Application.R
  R/ContentHandlers.R
  R/HTTPError.R
  R/zzz.R
  inst/tinytest/test-app-content-handlers.R
  inst/tinytest/test-cl-application.R
  inst/tinytest/test-cl-content-handler.R
  inst/tinytest/test-cl-http-error.R
  inst/tinytest/test-cl-request.R
  inst/tinytest/test-cl-response.R
  man/Application.Rd
  man/ContentHandlers.Rd
  man/HTTPError.Rd
  man/raise.Rd
Labels: docs, testing

#83 Body params
  R/RcppExports.R
  R/Request.R
  inst/tinytest/test-cl-request.R
  inst/tinytest/test-parse-multipart.R
  man/Request.Rd
  src/RcppExports.cpp
  src/parse_multipart.cpp
  src/url_decode.cpp
  src/url_encode.cpp
Labels: core, enhancement, usability

#85 rework process_request - now eval everything with error handling
  R/Application.R
  inst/examples/middleware/app.R
  inst/tinytest/test-app-static.R
  inst/tinytest/test-cl-application.R
  inst/tinytest/test-misc.R
Labels: bug, core, testing

#88 Rework tests
  R/Response.R
  inst/examples/content-handlers/app.R
  inst/tinytest/test-app-auth-basic.R
  inst/tinytest/test-app-auth-bearer.R
  inst/tinytest/test-app-compress.R
  inst/tinytest/test-app-content-handlers.R
  inst/tinytest/test-app-hello.R
  inst/tinytest/test-app-middleware.R
  inst/tinytest/test-app-openapi.R
  inst/tinytest/test-app-plot.R
  inst/tinytest/test-app-static.R
  inst/tinytest/test-cl-application.R
  inst/tinytest/test-cl-content-handler.R
  inst/tinytest/test-cl-request.R
  inst/tinytest/test-cl-response.R
  inst/tinytest/test-cl-router.R
  inst/tinytest/test-misc.R
Labels: testing

#89 Improve coverage for the C++
  inst/tinytest/test-date.R
  inst/tinytest/test-format-headers.R
  inst/tinytest/test-parse-multipart.R
  src/RcppExports.cpp
  src/date.cpp
  src/parse_multipart.cpp
Labels: testing
