Repository rexyai/RestRserve, pull requests merged in 2019-08, with the labels that each got.

#46 Migrate to Rcpp
  .lintr
  DESCRIPTION
  NAMESPACE
  R/RcppExports.R
  R/RestRserveRequest.R
  R/utils.R
  R/zzz.R
  src/.gitignore
  src/Makevars
  src/Makevars.win
  src/RcppExports.cpp
  src/escape_chars.c
  src/escape_chars.cpp
  src/format_headers.cpp
  src/parse_cookies.cpp
  src/parse_headers.cpp
  src/register.c
  src/types.h
  src/url_decode.cpp
  src/url_encode.cpp
  src/utils.cpp
  src/utils.h
  tests/testthat/test-format-headers.R
  tests/testthat/test-parse-cookies.R
  tests/testthat/test-parse-headers.R
  tests/testthat/test-url-encoding.R
Labels: enhancement

#50 Add ';' to end for the Set-Cookie header
  src/format_headers.cpp
  tests/testthat/test-format-headers.R
Labels: fix

#53 Jsonlite
  DESCRIPTION
  NAMESPACE
  R/RcppExports.R
  R/RestRserveAuthMiddleware.R
  R/json.R
  man/to_json.Rd
  src/RcppExports.cpp
  src/escape_chars.cpp
  tests/testthat/helper-curl.R
  tests/testthat/test-RestRserveResponse.R
  tests/testthat/test-deparse.R
  tests/testthat/test-json.R
Labels: enhancement

#56 Deduplicate and no collision for the handlers in add_route
  R/RestRserveApplication.R
Labels: enhancement

#60 Add use_cdn param to add_swagger_ui method
  R/RestRserveApplication.R
Labels: enhancement, usability

#47 Add methods to response and request
  R/RcppExports.R
  R/RestRserveRequest.R
  R/RestRserveResponse.R
  R/utils.R
  src/RcppExports.cpp
  src/format_cookies.cpp
  src/format_headers.cpp
  src/utils.cpp
  src/utils.h
  tests/testthat/test-RestRserveRequest.R
  tests/testthat/test-RestRserveResponse.R
  tests/testthat/test-date.R
  tests/testthat/test-format-cookies.R
  tests/testthat/test-format-headers.R
  tests/testthat/test-misc.R
Labels: WIP, core, enhancement, usability

#57 [WIP] draft for lgr signatures
  DESCRIPTION
  NAMESPACE
  R/RestRserveApplication.R
  R/logging.R
  examples/api-key-authentication/app.R
  man/Logger.Rd
  man/RestRserveApplication.Rd
  man/logging_constants.Rd
  tests/testthat/helper-app-auth.R
  tests/testthat/helper-app-basic.R
  tests/testthat/helper-app-swagger.R
  tests/testthat/test-logging.R
Labels: WIP, core

#63 Multipart request body parser
  .gitignore
  R/RcppExports.R
  R/RestRserveRequest.R
  src/Makevars
  src/Makevars.win
  src/RcppExports.cpp
  src/format_cookies.cpp
  src/format_headers.cpp
  src/multipart.cpp
  src/nonstd/string_view.hpp
  src/parse_cookies.cpp
  src/parse_headers.cpp
  src/url_decode.cpp
  src/url_encode.cpp
  src/utils.cpp
  src/utils.h
  tests/testthat/helper-multipart.R
  tests/testthat/test-RestRserveRequest.R
  tests/testthat/test-multipart.R
  tests/testthat/test-parse-cookies.R
Labels: core, enhancement, help wanted

#64 Export to_http_date and from_http_date
  NAMESPACE
  R/date.R
  R/utils.R
  man/http-date.Rd
Labels: enhancement, usability

#69 Add tests
  DESCRIPTION
  inst/tinytest/test-cl-application.R
  inst/tinytest/test-cl-auth-backend.R
  inst/tinytest/test-cl-auth-barear.R
  inst/tinytest/test-cl-auth-mw.R
  inst/tinytest/test-cl-auth.basic.R
  inst/tinytest/test-cl-content-handler.R
  inst/tinytest/test-cl-error.R
  inst/tinytest/test-cl-request.R
  inst/tinytest/test-cl-response.R
  inst/tinytest/test-cl-router.R
  inst/tinytest/test-date.R
  inst/tinytest/test-format-cookies.R
  inst/tinytest/test-logging.R
  inst/tinytest/test-openapi.R
Labels: testing
